version: "3.8"
services:

  mysqldb:
    image: "mysql:8.0"
    volumes:
      - /Users/serdar/dockerdata/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"

  redis:
    image: "redis:latest"
    hostname:
      redis
    ports:
      - "6379:6379"

  console1:
    image: "console1:${CONSOLE1_VER}"
    scale: 3
    env_file:
      - ./console1/.env.development

  logger:
    image: "logger:${LOGGER_VER}"
    scale: 3
    env_file:
      - ./logger/.env.development

  hello:
    image: "hello:${HELLO_VER}"
    scale : 1
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    env_file:
      - ./hello/.env.development